services:

  frontend:
      build:
           context: ./webapp-withdocker/.          
      image: frontend
      container_name: frontend
      ports:
            - 5009:8080
  api:
       build:
            context: ./backend/.
       image: api
       container_name: api
       ports:
            - 5236:8080
  database:
       image: mcr.microsoft.com/mssql/server:2022-latest
       container_name: database
       environment:
                - ACCEPT_EULA=Y
                - SA_PASSWORD=YourStrongP@ssw0rd
       ports:
            - 1433:1433
